"""API exception hierarchy and FastAPI exception handlers.

Every error is returned as a structured JSON body:

    {
        "success": false,
        "request_id": "<uuid>",
        "error": {"code": "...", "message": "..."}
    }

Handlers are registered on the application by ``register_exception_handlers``.
"""

import logging
from typing import Optional

from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from app.api.models import ErrorDetail, ErrorResponse

logger = logging.getLogger(__name__)


class APIError(Exception):
    """Base class for all API-level errors."""

    status_code: int = 500
    code: str = "INTERNAL_ERROR"
    default_message: str = "Unexpected server error."

    def __init__(self, message: Optional[str] = None) -> None:
        self.message = message or self.default_message
        super().__init__(self.message)


class InvalidURLError(APIError):
    """HTTP 400: the request body is missing, invalid, or not a video URL."""

    status_code = 400
    code = "INVALID_URL"
    default_message = "Invalid TikTok video URL."


class VideoNotFoundError(APIError):
    """HTTP 404: TikTok could not be made to return comments for the video."""

    status_code = 404
    code = "VIDEO_NOT_FOUND"
    default_message = "Unable to retrieve comments for this video."


class RateLimitedError(APIError):
    """HTTP 429: TikTok temporarily rejected the request."""

    status_code = 429
    code = "RATE_LIMITED"
    default_message = "TikTok temporarily rejected the request."


class InternalError(APIError):
    """HTTP 500: unexpected server error."""

    status_code = 500
    code = "INTERNAL_ERROR"
    default_message = "Unexpected server error."


def _request_id(request: Request) -> str:
    """Return the request ID generated by the request-id middleware."""
    return str(getattr(request.state, "request_id", ""))


def _error_response(request_id: str, error: APIError) -> ErrorResponse:
    """Build the structured JSON error body for ``error``."""
    return ErrorResponse(
        success=False,
        request_id=request_id,
        error=ErrorDetail(code=error.code, message=error.message),
    )


def register_exception_handlers(app: FastAPI) -> None:
    """Register every exception handler on ``app``."""

    @app.exception_handler(APIError)
    async def api_error_handler(request: Request, exc: APIError) -> JSONResponse:
        request_id = _request_id(request)
        logger.error(
            "Scrape failed request_id=%s error_code=%s error_message=%r",
            request_id,
            exc.code,
            exc.message,
        )
        return JSONResponse(
            status_code=exc.status_code,
            content=_error_response(request_id, exc).model_dump(),
        )

    @app.exception_handler(RequestValidationError)
    async def validation_error_handler(
        request: Request, exc: RequestValidationError
    ) -> JSONResponse:
        request_id = _request_id(request)
        logger.warning(
            "Invalid request request_id=%s errors=%r",
            request_id,
            exc.errors(),
        )
        return JSONResponse(
            status_code=400,
            content=_error_response(request_id, InvalidURLError()).model_dump(),
        )

    @app.exception_handler(HTTPException)
    async def http_error_handler(request: Request, exc: HTTPException) -> JSONResponse:
        request_id = _request_id(request)
        code = "NOT_FOUND" if exc.status_code == 404 else f"HTTP_{exc.status_code}"
        logger.warning(
            "HTTP error request_id=%s status=%d detail=%r",
            request_id,
            exc.status_code,
            exc.detail,
        )
        return JSONResponse(
            status_code=exc.status_code,
            content=ErrorResponse(
                success=False,
                request_id=request_id,
                error=ErrorDetail(code=code, message=str(exc.detail)),
            ).model_dump(),
        )

    @app.exception_handler(Exception)
    async def unhandled_error_handler(request: Request, exc: Exception) -> JSONResponse:
        request_id = _request_id(request)
        logger.exception(
            "Unexpected error request_id=%s error=%r",
            request_id,
            exc,
        )
        return JSONResponse(
            status_code=500,
            content=_error_response(request_id, InternalError()).model_dump(),
        )
